@startuml
skinparam componentStyle uml2

package "Поликлиника" {
    [Информационная система] as IS
}

IS - [Учет больных]
IS - [Запись на прием]
IS - [Учет приема]
IS - [Медицинская карта]

[Учет больных] ..> [Медицинская карта] : содержит
[Запись на прием] ..> [Медицинская карта] : содержит
[Учет приема] ..> [Медицинская карта] : содержит

@enduml

